services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/data?schema=public"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
